### ISSUE TITLE
Not applicable to the explicit method

### ISSUE THREAD

**Issue by noneeexist** [costerwi/abaqus-signed-mises#1]
After testing, it appears that the script only works with odb files using the static general method. 
How can I apply it to the dynamic explicit method?

```
C:\...\...>abaqus python s_mises.py Drop.odb
Step-1 Increment    111167: Step Time =   5.0000E-04
Traceback (most recent call last):
  File "s_mises.py", line 99, in <module>
    fromOdb(odbName = arg)
  File "s_mises.py", line 87, in fromOdb
    calculate(frame)
  File "s_mises.py", line 69, in calculate
    data=sign_trace(Sblock.data)*MISESblock.data,
  File "s_mises.py", line 45, in sign_trace
    assert 6 == A.shape[1], "Data elements must be in Abaqus symmetric tensor format"
AssertionError: Data elements must be in Abaqus symmetric tensor format
```

**Comment by costerwi** [comment]
I'll investigate.

What version of Abaqus are you using?

Is your model 2D, axisymmetric, or shell elements by chance? The calculation is expecting a 3D continuum stress right now but I should be able to make exceptions for these others.

Thanks

**Comment by noneeexist** [comment]
Thank you for your response. 

I'm using Abaqus 2022. 
The model includes 3D stress, continuous shell, and discrete rigid elements.

**Comment by costerwi** [comment]
I didn't mean to close this issue yet.
Please try the new release v1.1.0 and let me know if that works for you.

**Comment by noneeexist** [comment]
It works very well. Thank you for the update!
